import 'package:flutter/material.dart';
import 'package:restaurant_app/MaterialSearchResults.dart';
import 'package:restaurant_app/Trie.dart';
import 'package:restaurant_app/RestaurantCardViewer/ResultsPage.dart';
import 'package:restaurant_app/UserPreferences/User.dart';

class MaterialSearch extends StatefulWidget {
  _MaterialSearchState hP;
  @override
  _MaterialSearchState createState() => hP;

  MaterialSearch(lat, lon) {
    hP = new _MaterialSearchState(lat, lon, null);
  }

  MaterialSearch.withUser(lat, lon, user) {
    hP = new _MaterialSearchState(lat, lon, user);
  }
}

class _MaterialSearchState extends State<MaterialSearch> {
  noSuchMethod(Invocation i) => super.noSuchMethod(i);

  FocusNode myFocusNode;

  @override
  void dispose() {
    // Clean up the focus node when the Form is disposed
    myFocusNode.dispose();

    super.dispose();
  }

  double _lat, _lon;

  Set<String> _selectedCuisines;
  List<String> _cuisines;
  Trie _trie;
  User _user;
  _MaterialSearchState(this._lat, this._lon, this._user) {
    _selectedCuisines = Set();
    _cuisines = [
      'Abruzzese',
      'Acai Bowls',
      'Afghan',
      'African',
      'Alentejo',
      'Algarve',
      'Alsatian',
      'Altoatesine',
      'American',
      'Andalusian',
      'Apulian',
      'Arab Pizza',
      'Arabian',
      'Argentine',
      'Armenian',
      'Arroceria / Paella',
      'Asian Fusion',
      'Asturian',
      'Australian',
      'Austrian',
      'Auvergnat',
      'Azores',
      'Backshop',
      'Baden',
      'Bagels',
      'Baguettes',
      'Bakeries',
      'Bangladeshi',
      'Barbeque',
      'Basque',
      'Bavarian',
      'Beer',
      'Beer Garden',
      'Beer Hall',
      'Beira',
      'Beisl',
      'Belgian',
      'Bento',
      'Berrichon',
      'Beverage Store',
      'Bistros',
      'Black Sea',
      'Blowfish',
      'Bourguignon',
      'Brasseries',
      'Brazilian Empanadas',
      'Brazilian',
      'Breakfast & Brunch',
      'Breweries',
      'Brewpubs',
      'British',
      'Bubble Tea',
      'Buffets',
      'Bulgarian',
      'Burgers',
      'Burmese',
      'Butcher',
      'CSA',
      'Cafes',
      'Cafeteria',
      'Cajun/Creole',
      'Calabrian',
      'Cambodian',
      'Canadian',
      'Candy Stores',
      'Canteen',
      'Cantonese',
      'Caribbean',
      'Catalan',
      'Central Brazilian',
      'Chee Kufta',
      'Cheese Shops',
      'Cheesesteaks',
      'Chicken Shop',
      'Chicken Wings',
      'Chilean',
      'Chimney Cakes',
      'Chinese',
      'Chocolatiers & Shops',
      'Churros',
      'Cideries',
      'Coffee & Tea Supplies',
      'Coffee & Tea',
      'Coffee Roasteries',
      'Colombian',
      'Comfort Food',
      'Congee',
      'Convenience Stores',
      'Conveyor Belt Sushi',
      'Corsican',
      'Creperies',
      'Cuban',
      'Cucina campana',
      'Cupcakes',
      'Curry Sausage',
      'Custom Cakes',
      'Cypriot',
      'Czech',
      'Czech/Slovakian',
      'Dagashi',
      'Danish',
      'Delicatessen',
      'Delis',
      'Desserts',
      'Dim Sum',
      'Diners',
      'Dinner Theater',
      'Distilleries',
      'Do-It-Yourself Food',
      'Dominican',
      'Donairs',
      'Donburi',
      'Donuts',
      'Dried Fruit',
      'Dumplings',
      'Eastern European',
      'Eastern German',
      'Eastern Mexican',
      'Egyptian',
      'Emilian',
      'Empanadas',
      'Ethical Grocery',
      'Ethiopian',
      'Fado Houses',
      'Falafel',
      'Farmers Market',
      'Fast Food',
      'Filipino',
      'Fischbroetchen',
      'Fish & Chips',
      'Fishmonger',
      'Flatbread',
      'Flemish',
      'Fondue',
      'Food Court',
      'Food Delivery Services',
      'Food Stands',
      'Food Trucks',
      'Franconian',
      'Freiduria',
      'French Southwest',
      'French',
      'Friterie',
      'Friulan',
      'Frozen Food',
      'Fruits & Veggies',
      'Fuzhou',
      'Galician',
      'Game Meat',
      'Gastropubs',
      'Gelato',
      'Georgian',
      'German',
      'Giblets',
      'Gluten-Free',
      'Gozleme',
      'Greek',
      'Grocery',
      'Guamanian',
      'Gyudon',
      'Hainan',
      'Haitian',
      'Hakka',
      'Halal',
      'Hand Rolls',
      'Hawaiian',
      'Hawker Centre',
      'Health Markets',
      'Henghwa',
      'Herbs & Spices',
      'Hessian',
      'Heuriger',
      'Himalayan/Nepalese',
      'Hokkien',
      'Homemade Food',
      'Honduran',
      'Honey',
      'Hong Kong Style Cafe',
      'Horumon',
      'Hot Dogs',
      'Hot Pot',
      'Hunan',
      'Hungarian',
      'Iberian',
      'Ice Cream & Frozen Yogurt',
      'Imported Food',
      'Indian',
      'Indonesian',
      'International Grocery',
      'International',
      'Internet Cafes',
      'Irish',
      'Island Pub',
      'Israeli',
      'Italian',
      'Izakaya',
      'Jaliscan',
      'Japanese Curry',
      'Japanese Sweets',
      'Japanese',
      'Jewish',
      'Juice Bars & Smoothies',
      'Kaiseki',
      'Kebab',
      'Kiosk',
      'Kombucha',
      'Kopitiam',
      'Korean',
      'Kosher',
      'Kurdish',
      'Kushikatsu',
      'Lahmacun',
      'Laos',
      'Laotian',
      'Latin American',
      'Lebanese',
      'Ligurian',
      'Live/Raw Food',
      'Lumbard',
      'Lyonnais',
      'Macarons',
      'Madeira',
      'Malaysian',
      'Mamak',
      'Mauritius',
      'Meat Shops',
      'Meatballs',
      'Mediterranean',
      'Mexican',
      'Middle Eastern',
      'Milk Bars',
      'Milkshake Bars',
      'Minho',
      'Modern Australian',
      'Modern European',
      'Mongolian',
      'Moroccan',
      'Mulled Wine',
      'Napoletana',
      'Nasi Lemak',
      'New Mexican Cuisine',
      'New Zealand',
      'Nicaraguan',
      'Nicoise',
      'Night Food',
      'Nikkei',
      'Noodles',
      'Norcinerie',
      'Northeastern Brazilian',
      'Northern Brazilian',
      'Northern German',
      'Northern Mexican',
      'Nyonya',
      'Oaxacan',
      'Oden',
      'Okinawan',
      'Okonomiyaki',
      'Olive Oil',
      'Onigiri',
      'Open Sandwiches',
      'Organic Stores',
      'Oriental',
      'Ottoman Cuisine',
      'Oyakodon',
      'PF/Comercial',
      'Pakistani',
      'Palatine',
      'Pan Asian',
      'Panzerotti',
      'Parent Cafes',
      'Parent Cafes',
      'Parma',
      'Pasta Shops',
      'Patisserie/Cake Shop',
      'Pekinese',
      'Persian/Iranian',
      'Peruvian',
      'Piadina',
      'Piemonte',
      'Pierogis',
      'Pita',
      'Pizza',
      'Poke',
      'Polish',
      'Polynesian',
      'Pop-Up Restaurants',
      'Popcorn Shops',
      'Portuguese',
      'Potatoes',
      'Poutineries',
      'Pretzels',
      'Provencal',
      'Pub Food',
      'Pueblan',
      'Puerto Rican',
      'Ramen',
      'Reunion',
      'Rhinelandian',
      'Ribatejo',
      'Rice',
      'Robatayaki',
      'Rodizios',
      'Roman',
      'Romanian',
      'Rotisserie Chicken',
      'Russian',
      'Salad',
      'Salumerie',
      'Salvadoran',
      'Sandwiches',
      'Sardinian',
      'Scandinavian',
      'Schnitzel',
      'Scottish',
      'Seafood Markets',
      'Seafood',
      'Senegalese',
      'Serbo Croatian',
      'Shanghainese',
      'Shaved Ice',
      'Shaved Snow',
      'Sicilian',
      'Signature Cuisine',
      'Singaporean',
      'Slovakian',
      'Smokehouse',
      'Soba',
      'Soul Food',
      'Soup',
      'South African',
      'Southern',
      'Spanish',
      'Specialty Food',
      'Sri Lankan',
      'Steakhouses',
      'Street Vendors',
      'Sugar Shacks',
      'Sukiyaki',
      'Supper Clubs',
      'Sushi Bars',
      'Swabian',
      'Swedish',
      'Swiss Food',
      'Syrian',
      'Szechuan',
      'Tabernas',
      'Tacos',
      'Taiwanese',
      'Taiyaki',
      'Takoyaki',
      'Tamales',
      'Tapas Bars',
      'Tapas/Small Plates',
      'Tavola Calda',
      'Tea Rooms',
      'Tempura',
      'Teochew',
      'Teppanyaki',
      'Tex-Mex',
      'Thai',
      'Themed Cafes',
      'Tofu Shops',
      'Tonkatsu',
      'Torshi',
      'Tortillas',
      'Traditional American',
      'Traditional Norwegian',
      'Traditional Swedish',
      'Tras-os-Montes',
      'Trattorie',
      'Trinidadian',
      'Turkish Ravioli',
      'Turkish',
      'Tuscan',
      'Udon',
      'Ukrainian',
      'Unagi',
      'Uzbek',
      'Vegan',
      'Vegetarian',
      'Venetian',
      'Venezuelan',
      'Venison',
      'Vietnamese',
      'Waffles',
      'Water Stores',
      'Western Style Japanese Food',
      'Wine Tasting Room',
      'Wineries',
      'Wok',
      'Wraps',
      'Yakiniku',
      'Yakitori',
      'Yucatan',
      'Yugoslav',
      'Zapiekanka',
      'Wine & Spirits'
    ];

    _trie = Trie.list(_cuisines);
  }



  @override
  void initState() {
    myFocusNode = FocusNode();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: "Basic List",
      home: Scaffold(
        backgroundColor: Theme.of(context).backgroundColor,
        appBar: AppBar(
            backgroundColor: Theme
                .of(context)
                .primaryColor,
            title: Row(
              children: <Widget>[
//                Container(
//                  padding: EdgeInsets.only(right: 5.0),
//                  child: new Chip(
//                    avatar: new CircleAvatar(
//                      backgroundColor: Colors.grey.shade800,
//                      child: new Text('AB'),
//                    ),
//                    label: new Text('Aaron Burr'),
//                  ),
//                ),
                Flexible(
                  child: TextField(
                    autofocus: true,
                    focusNode: myFocusNode,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16.0,
                    ),
                    decoration: InputDecoration(
                      border: InputBorder.none,
                      hintText: 'Search',
                      hintStyle: TextStyle(
                        color: Colors.white,
                        fontSize: 16.0,
                      ),
                    ),
                    onSubmitted: (text) {
                      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => ResultsPage.cuisines(_lat, _lon, _selectedCuisines, _user)),
                      );
                    },
                    onChanged: (text) {
                      setState(() {
                        _cuisines = _trie.getAllWordsWithPrefix(text);
                      });
                    },
                  ),
                )
              ],
            ),
            actions: <Widget>[
              new IconButton(
                icon: new Icon(Icons.search),
                tooltip: 'Search',
                onPressed: () => FocusScope.of(context).reparentIfNeeded(myFocusNode),
              ),
            ]
        ),
        floatingActionButton: FloatingActionButton(
          tooltip: "SEARCH",
          child: new Icon(Icons.arrow_forward),
          backgroundColor: Theme.of(context).primaryColor,
          foregroundColor: Colors.white,
          onPressed: () {
            Navigator.pushReplacement(context, MaterialPageRoute(
                builder: (context) =>
                    ResultsPage.cuisines(_lat, _lon, _selectedCuisines, _user)),
            );
          }),
        body: Container(child: MaterialSearchResults(_cuisines, _selectedCuisines, this))
      ),
    );
  }
}
